texto = input('digite uma frase ou palavra: ')
quantidade_vogais = texto.count('a')
quantidade_vogais += texto.count('e')
quantidade_vogais += texto.count('i')
quantidade_vogais += texto.count('o')
quantidade_vogais += texto.count('u')

quantidade = texto.count('b')
quantidade += texto.count('c')
quantidade += texto.count('d')
quantidade += texto.count('f')
quantidade += texto.count('g')
quantidade += texto.count('h')
quantidade += texto.count('j')
quantidade += texto.count('k')
quantidade += texto.count('l')
quantidade += texto.count('m')
quantidade += texto.count('n')
quantidade += texto.count('o')
quantidade += texto.count('p')
quantidade += texto.count('q')
quantidade += texto.count('r')
quantidade += texto.count('s')
quantidade += texto.count('t')
quantidade += texto.count('v')
quantidade += texto.count('w')
quantidade += texto.count('x')
quantidade += texto.count('y')
quantidade += texto.count('z')

print("Quantidade de vogais: ", quantidade_vogais, "Quantidade de consoantes: ", quantidade)